### PR TITLE
Add path when including conanbuildinfo.cmake (out-of-source builds)

### PR DESCRIPTION
**Pull request by jgsogo**
Adding ```CMAKE_BINARY_DIR``` allows out-of-source builds.

### CODE REVIEW

**Comment by dimi309** [comment]
Thanks again Javier!

**Comment by dimi309** [comment]
I've tried it locally with "conan test_package" and it does not seem to find conanbuildinfo.cmake... Shoud it be CMAKE_SOURCE_DIR?

**Comment by dimi309** [comment]
(I'm still not great at conan... or game development for that matter 😂)

**Comment by jgsogo** [comment]
Are the tests (travis/appveyor) running for pull requests?

**Comment by dimi309** [comment]
No, only for what I merge into master for now.

**Comment by dimi309** [comment]
I've been pushing a lot of changes these days, so they were consuming my processes, but maybe I've excluded too many things. Building pull requests could be useful :) Do you know what happens when the moment comes in the build to upload to conan though?

**Comment by jgsogo** [comment]
There two environment variables used to control the _upload moment_, so you can select whether to upload or not, the reference and channel:
 * ```CONAN_UPLOAD: 1```
 * ```CONAN_REFERENCE: "small3d/1.0.5"```
 * ```CONAN_CHANNEL="stable"```

Also, take a look to [this code](https://github.com/conan-io/conan-package-tools/blob/develop/conan/packager.py#L453), this is where the channel is selected/modified when you use conan_package_tools. I think there is a some work to be done in ```ConanMultiPackager``` class:
 * allow to upload binaries and recipe or only recipe (issue [here](https://github.com/conan-io/conan-package-tools/pull/26#issuecomment-243672109))
 * more control over those environment variable using branch names from github, or checking if it is a pull request or not,...

**Comment by dimi309** [comment]
Got it! Thanks. So I've re-enabled builds on the develop branch (which I had excluded before), activated building pull requests on Travis and disabled uploads (CONAN_UPLOAD removed from both travis and appveyor yml files). On appveyor I think there is no command to disable or enable building pull requests. Let's just see what happens next time.

**Pull request merged**
