### PR TITLE
fix test_package issue

### PR DESCRIPTION
**Pull request by jgsogo**
Fix error introduced in PR #37

The problem was, when invoking ```conan test_package```
 * ```conan``` selects where to build the package, in this case: ```.../small3d/1.0.5/coding3d/ci/build/<hash>/```

```
small3d/1.0.5@coding3d/ci: WARN: Forced build from source
small3d/1.0.5@coding3d/ci: Building your package in ~/.conan/data/small3d/1.0.5/coding3d/ci/build/ec41054f33cd1b615a1cb43233780b28ec84d560
small3d/1.0.5@coding3d/ci: Copying sources to build folder
small3d/1.0.5@coding3d/ci: Generated cmake created conanbuildinfo.cmake
```

 * and creates the ```conanbuildinfo.cmake``` file there
 * ... so on package recipe, at function ```Small3dConan::build``` we cannot set a custom build folder and keep using ```INCLUDE(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)``` :confused: ([here](http://conanio.readthedocs.io/en/latest/packaging/creating_in.html#creating-the-package-recipe) uses default build folder)

    (btw, my recipe [here](https://github.com/jgsogo/conan-portaudio/blob/v19.20140130/conanfile.py) would have failed for the same reason if it had conan dependencies)

### CODE REVIEW

**Comment by dimi309** [comment]
Now small3d package's test package builds ok, but I can't build the games. Have you managed to build them locally with CMAKE_BINARY_DIR used in the cmake file?

**Comment by dimi309** [comment]
Btw, the games are just projects referencing conan packages, they are not packages themselves... Would this still work with them?

**Comment by jgsogo** [comment]
I'm able to build the games using the following:

```
conan export coding3d/stable
mkdir build-avoid
cd build-avoid
conan install ../samples/AvoidTheBug3D/
cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_CONAN:BOOL=TRUE
cmake --build .
```

and also:

```
conan export coding3d/stable
cd samples/AvoidTheBug3D/
conan install .
cmake . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_CONAN:BOOL=TRUE
cmake --build .
```

**Comment by dimi309** [comment]
Maybe exporting and installing it makes the whole difference I guess... I set the variable back to CONAN_SOURCE_DIR for now but I wonder what is the best way. Are we supposed to export projects, even if we do not plan to upload them to conan or make packages? Take a user who just wants to use libaries from conan and who is building an application that is not a package for example. Should he be instructed to run "conan export"?

(And an unrelated question, how did you learn all this stuff? I'm still struggling :scream: )

**Comment by dimi309** [comment]
(btw I meant I set the variable back to CONAN_SOURCE_DIR for the games. small3d itself works with CONAN_BINARY_DIR after your latest pull request)

**Pull request merged**
